### ISSUE TITLE
[Feature request] Implement support for Proton's Wine full screen hack

### ISSUE THREAD

**Issue by leonmaxx** [sarnex/wine-d3d9-patches#10]
Hello Sarnex,

I'm using Wine from Valve/Proton repository with your wine-d3d patches applied ([link](https://github.com/leonmaxx/wine-proton)).  

Proton's Wine have full screen hack code for OpenGL and Vulkan that avoids changing display resolution and scales application output to fit default display resolution. I'm asking You to add support for Proton's full screen hack (probably as separate patch), or give any tips on how to implement it myself.  

Sorry for my bad english. BR, Leon.

**Comment by sarnex** [comment]
Hi Leon,

This repository is specifically for the gallium nine patches. I think it would murk up the repository to start accepting patches unrelated to gallium nine. To me, it makes more sense for this to be added to wine staging, which my patches apply on top of.

Thanks,
Sarnex

**Comment by leonmaxx** [comment]
Hello Sarnex,

It's right about gallium-nine support for Proton's full screen hack, specifically wrapper dll `d3d9-nine.dll`.  
Can You at least give some hints to implement it myself?  

I think it needs changes in present.c and dri3.c: get real window size from wine and use it in presentation functions as destination rectangle. Am I right?

Thanks, Leon.

**Comment by sarnex** [comment]
Unfortunately I am not familiar with the present/dri3 code. You can try asking in the #d3d9 channel on freenode.

**Comment by leonmaxx** [comment]
Ok, thanks for hint.
