### ISSUE TITLE
ellaborate on the readme

### ISSUE THREAD

**Issue by tatsujb** [sarnex/wine-d3d9-patches#11]
I have no idea how to use this?

say I'm on an ubuntu 18.10 and I want to have wine gallium 9 : 

from what I understand it is possible to do this by installing wine-staging as you normally would then applying some sort of patch to that?

could you give me a step by step of this?

does this somewhat fit? https://askubuntu.com/a/326049/307184

I would imagine that guide no longer works as it is severely outdated.

**Comment by sarnex** [comment]
This repo is for advanced users who need to patch wine themselves.

You can just use my PPA.

https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3

**Comment by tatsujb** [comment]
does not work for ubuntu 18.10 there is no release candidate

**Comment by sarnex** [comment]
I will add support for cosmic, please try the PPA in a few hours
