### ISSUE TITLE
Gallium Nine no longer increases FPS in StarCraft 2. Probably needs rebase after the latest Wine commit.

### ISSUE THREAD

**Issue by zefkerr** [sarnex/wine-d3d9-patches#12]
Hi! Gallium Nine no longer increases FPS in StarCraft 2 if I use the newest  [Wine commit](https://source.winehq.org/git/wine.git/commit/f7b3120991df02ecaa975c18c6421fedb48ae731).
I can assume that this began to happen after [this Wine commit](https://source.winehq.org/git/wine.git/commit/c74c8800b3e8b2f89a43c38b9d90de675abae0ae) but at the moment I have not checked this statement. But I know for sure that this does not happen if I use this commit. If this helps you, then I can try rebuilding Wine several times using different commits to find out exactly which commit causes Gallium Nine to fail. Should I do this?
Thank you.

**Comment by sarnex** [comment]
This is just a repo for patches. Please report your issue here:

https://github.com/iXit/Mesa-3D/issues

Sarnex

**Comment by zefkerr** [comment]
OK, Thank you.
