### ISSUE TITLE
Wine 4.2 rebase?

### ISSUE THREAD

**Issue by zefkerr** [sarnex/wine-d3d9-patches#13]
Hi, @sarnex !
What about Wine 4.2 rebase, please? Why only 4.0?

**Comment by FireBurn** [comment]
Have you tried applying the 4.0 patch on 4.2? There usually isn't much
difference between them

**Comment by zefkerr** [comment]
@FireBurn 
![screenshot from 2019-02-10 14-00-06](https://user-images.githubusercontent.com/36989404/52944663-c468fc80-3391-11e9-9d67-9df6acc4ee7b.png)

**Comment by sarnex** [comment]
Staging removed the dll redirects and I'm trying to backport some patches for nine standalone to get it to work

**Comment by sarnex** [comment]
Just discussed with the team. Patching a full wine build is not going to be supported after 4.1. Please use wine-nine-standalone for 4.2+
