### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by madsam84** [sarnex/wine-d3d9-patches#2]
From the last time I have problem with displaying textures in World of Warcraft 3.3.5 (in other games not tested)
with d3d9: http://i.piccy.info/i9/a8c6f74e78a0541d49d55ffb9469e4b4/1507565562/134054/1186269/Screenshot_with_enabled_d3d9.jpg
without: http://i.piccy.info/i9/651f44f3b1f3a66df21fcb3cf17dd854/1507565695/136128/1186269/Screenshot_without_enabled_d3d9.jpg

**Comment by sarnex** [comment]
@junked Please report this upstream at https://github.com/iXit/Mesa-3D/issues

Also, please note I added the following patch for the first time in the 2.19 release, so it may be related:
https://github.com/iXit/wine/commit/82dc2a06fca70a14d3b00833dc0b83e6fa09ea85
