### ISSUE TITLE
Hi! Wine Staging 3.4 released. What about the update of these patches?

### ISSUE THREAD

**Issue by zefkerr** [sarnex/wine-d3d9-patches#3]
Hi! Wine Staging 3.4 released. What about the update of these patches?

**Comment by sarnex** [comment]
Hi,

I have to manually rebase these patches on every Wine release. Wine 3.4 was released yesterday. Please allow up to a week for me before letting me know.

Thanks,
Sarnex

**Comment by sarnex** [comment]
Wine staging 3.4 has actually not released. If you check the below link, you will notice there is no
'Release 3.4' commit.

Also, I have to manually rebase these patches. If staging was released yesterday, please allow up to a week before letting me know.

Thanks,
Sarnex

https://github.com/wine-staging/wine-staging/commits/master

**Comment by jerbmega** [comment]
Wine-staging 3.4 *has* released, actually.

[Commit afe4f54bb439cfa26ca72968cec2da357ea8836e](https://github.com/wine-mirror/wine/commit/afe4f54bb439cfa26ca72968cec2da357ea8836e) is Wine 3.4, and on the wine-staging repo there is a commit which rebases to that commit, [which also has the tag 3.4](https://github.com/wine-staging/wine-staging/releases/tag/v3.4).

**Comment by sarnex** [comment]
You may notice that many previous commits have the tag, which means it will be part of the release. I have been following staging for a very long time, and the final release is always signified with the 'Release X' commit. You will notice there was a 'Release 3.3' commit.

Usually they change the patchinstall.sh to print 'Staging X.X' instead of 'Staging X.X Unreleased' in that commit, but they did it in the rebase. It looks like a mistake. I am going to email them to confirm.

Again, please give me time to rebase even if it has released.

**Comment by zefkerr** [comment]
> @sarnex: You may notice that many previous commits have the tag, which means it will be part of the release. I have been following staging for a very long time, and the final release is always signified with the 'Release X' commit. You will notice there was a 'Release 3.3' commit.
Usually they change the patchinstall.sh to print 'Staging X.X' instead of 'Staging X.X Unreleased' in that commit, but they did it in the rebase. It looks like a mistake. I am going to email them to confirm.
Again, please give me time to rebase even if it has released.

Here you can download the source code of Wine Staging 3.4 release.
I already use it.
https://github.com/wine-staging/wine-staging/releases
![screenshot from 2018-03-17 22-38-07](https://user-images.githubusercontent.com/36989404/37558334-3e975442-2a34-11e8-8722-bd7b5967c0d3.png)

**Comment by sarnex** [comment]
I need to confirm the release practices with the developers going forward.

I will rebase my patches when I hear back

Sarnex

**Comment by zefkerr** [comment]
> @sarnex: I need to confirm the release practices with the developers going forward.
I will rebase my patches when I hear back

But WS3.4 release is already here in fact...
https://github.com/wine-staging/wine-staging/releases

**Comment by sarnex** [comment]
To be honest, I don't know how to explain what I'm doing any further. I
need to confirm the release practices with the new maintainers, because it has
significantly changed. If you absolutely need these patches on top of 3.4
immediately, please rebase yourself.

**Comment by sarnex** [comment]
The developers confirmed they made a mistake in the release by not doing the 'Release' commit. I have pushed 3.4

**Comment by chewi** [comment]
Thanks for turning this around so quickly, Nick.

**Comment by zefkerr** [comment]
> @sarnex: The developers confirmed they made a mistake in the release by not doing the 'Release' commit. I have pushed 3.4

Thank you very much!
