### ISSUE TITLE
Patches for the Wine 3.0 stable branch?

### ISSUE THREAD

**Issue by jorgicio** [sarnex/wine-d3d9-patches#7]
Hi!

I'm using the Stable branch of wine-vanilla in Gentoo. I used the 2.0 patch for that version, but I want to upgrade to the 3.0 stable (i.e. wine 3.0.2), however, there's no patch for that version. Now I'm requesting that patch, please.

Thanks!

**Comment by sarnex** [comment]
Does the 2.21 or 3.3 one not apply? These patches very rarely change.

**Comment by jorgicio** [comment]
Tried with 3.3, but failed, but 2.21 works fine here.
Thanks.

**Comment by sarnex** [comment]
No problem. Closing.
