### ISSUE TITLE
Inquire about your thoughts on wine-d3d9 in relation to ValveSoftware/wine

### ISSUE THREAD

**Issue by boombatower** [sarnex/wine-d3d9-patches#9]
See ValveSoftware/wine#9 and the mentioned parent issue. Not sure if they are interested or you, but figured I would make you aware as I am not familiar with the inner workings of wine.

I really appreciate your efforts as this works great, when the game is happy with it. :)

**Comment by sarnex** [comment]
Of course I would be happy to help. Valve would need to decide they want to include Nine though.
